#!/bin/sh

# rpi-kernel-build
# Copyright (C) 2020 Ryan Finnie
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

set -e

script_dir="$(dirname "$(readlink -f "$0")")"
if [ -z "${RC_FILE}" ]; then
  if [ -e "${script_dir}/rpi-kernel-build.rc" ]; then
    RC_FILE="${script_dir}/rpi-kernel-build.rc"
  fi
fi
if [ -n "${RC_FILE}" ]; then
  . "${RC_FILE}"
fi

[ -n "${GIT_CHECKOUT}" ] || GIT_CHECKOUT="${script_dir}/linux"
[ -n "${GIT_REMOTE}" ] || GIT_REMOTE="origin"
[ -n "${GIT_BRANCH}" ] || GIT_BRANCH="rpi-4.19.y"
[ -n "${IMAGE_DIR}" ] || IMAGE_DIR="${script_dir}/images"
[ -n "${CROSS_COMPILE}" ] || CROSS_COMPILE=""
[ -n "${DEFCONFIG}" ] || DEFCONFIG="bcm2711_defconfig"
[ -n "${JOBS}" ] || JOBS=4
[ -n "${BIS}" ] || BIS=0
[ -n "${GIT_FETCH}" ] || GIT_FETCH=1
[ -n "${BIS_SCRIPT}" ] || BIS_SCRIPT="${script_dir}/bcm2711-kernel-configure-bis"
[ -n "${EXTRA_REV}" ] || EXTRA_REV=""
[ -n "${TARBALL_BASE}" ] || TARBALL_BASE="bcm2711-kernel"

series_append=""
if [ "${DEFCONFIG}" = "bcm2711_defconfig" ]; then
  series_append="-p4"
fi

cd "${GIT_CHECKOUT}"

echo "Cleaning and updating repository"
make distclean ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" || true
rm -f .config.defconfig
git reset --hard
if [ "$GIT_FETCH" = 1 ]; then
  git fetch "${GIT_REMOTE}" "${GIT_BRANCH}"
fi
git checkout "${GIT_REMOTE}/${GIT_BRANCH}"
make distclean ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" || true
git_rev="$(git log -n1 --format="%h")"
git_date="$(git show -s --format=%ci "${git_rev}" | perl -ne '/^(\d{4})-(\d{2})-(\d{2})/ && print $1 . $2 . $3')"
extra_version="-${git_date}-g${git_rev}${EXTRA_REV}${series_append}"
if [ "$BIS" = 1 ]; then
  extra_version="${extra_version}-bis"
fi

echo "Configuring"
make ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" distclean || true
make ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" "${DEFCONFIG}"
scripts/config --set-str CONFIG_LOCALVERSION "${extra_version}"
if [ "$BIS" = 1 ]; then
  echo "Applying -bis changes"
  cp .config .config.defconfig
  . "${BIS_SCRIPT}"
fi
# LOCALVERSION="" doesn't override CONFIG_LOCALVERSION above.  It
# actually appends to it, but more importantly, it supresses "+"
# version appending.
make LOCALVERSION="" ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" olddefconfig
make LOCALVERSION="" ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" prepare

kernel_version="$(make LOCALVERSION="" ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" kernelrelease)"
if [ -e "${IMAGE_DIR}/${TARBALL_BASE}-${kernel_version}.tar.xz" ]; then
  echo "${IMAGE_DIR}/${TARBALL_BASE}-${kernel_version}.tar.xz exists, not compiling again"
  exit 0
fi

echo "Compiling"
make LOCALVERSION="" ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" -j${JOBS}

echo "Assembling tarball"
assemble_dir="$(mktemp -d)"
mkdir -p "${assemble_dir}" "${assemble_dir}/boot" "${assemble_dir}/boot/overlays"
make LOCALVERSION="" ARCH=arm64 CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_MOD_PATH="${assemble_dir}" modules_install
rm -f "${assemble_dir}/lib/modules"/*/source "${assemble_dir}/lib/modules"/*/build
cp arch/arm64/boot/Image "${assemble_dir}/boot/kernel8${series_append}.img"
cp COPYING "${assemble_dir}/boot/COPYING.linux"
cp .config "${assemble_dir}/boot/config${series_append}"
if [ -e .config.defconfig ]; then
  diff -u .config.defconfig .config >"${assemble_dir}/boot/config${series_append}-bis.diff" || true
fi
xz -9 -c <Module.symvers >"${assemble_dir}/boot/Module${series_append}.symvers.xz"
xz -9 -c <System.map >"${assemble_dir}/boot/System${series_append}.map.xz"
if [ "${DEFCONFIG}" = "bcm2711_defconfig" ]; then
  cp arch/arm64/boot/dts/broadcom/bcm*-rpi-4-*.dtb "${assemble_dir}/boot/"
  base64 -d <<"EOM" | gunzip -c >"${assemble_dir}/boot/armstub8-gic.bin"
H4sIAJ1SaF4CA9VQsUoDQRScu93iwGYNKQyG3JIfSDojWOwJ/sARSLDJVeInxCpbhPQRey2ChdUV
QbxKBfUDFt7VW1lrKm1cH1Z+gI0Dj3nz5hXD4O3epUAVocyjBJUp9ymT1gHRjSlbBIkx/C7NfJv8
bOHMdof0LfvMSKzTmxb1gAsI/lNt0mfsmQ4VgNLMXlzW1xjQizTnr8D6SEBNtKDV9OTjKYQ1YJ0A
miuBnYInYh3/3KyzSGv7ucc20E+e+/gDbI2+jn/rK87WjTFOpdlw5mEBmxvuI5Nm6Q9srnn3KbNE
dYh4Ce6GMzag8J6d6rvHEIYPYlJDzQP+Ib4BWs0hFgACAAA=
EOM
elif [ "${DEFCONFIG}" = "bcmrpi3_defconfig" ]; then
  cp arch/arm64/boot/dts/broadcom/bcm*-rpi-3-*.dtb "${assemble_dir}/boot/"
fi
cp arch/arm/boot/dts/overlays/README arch/arm/boot/dts/overlays/*.dtbo "${assemble_dir}/boot/overlays/"

find "${assemble_dir}" -type d -print0 | xargs -0 chmod 0755
find "${assemble_dir}" -type f -print0 | xargs -0 chmod 0644

mkdir -p "${IMAGE_DIR}"
tar Jcvf "${IMAGE_DIR}/${TARBALL_BASE}-${kernel_version}.tar.xz" --owner=root --group=root -C "${assemble_dir}" .

echo "Cleaning"
rm -rf "${assemble_dir}"

echo "Done"
