name: schedule
on:
  schedule:
  - cron: '34 5 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - arm
        - arm64
        branch:
        - rpi-5.4.y
        - rpi-5.8.y
        platform:
        - bcm2709
        - bcm2711
        - bcmrpi
        - bcmrpi3
        bis:
        - '0'
        - '1'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: raspberrypi/linux
        ref: ${{ matrix.branch }}
        path: linux
    - name: Dependency packages
      run: sudo apt-get -y install build-essential flex bison libssl-dev perl rsync gcc-aarch64-linux-gnu libc6-dev-arm64-cross gcc-arm-linux-gnueabi libc6-dev-armel-cross
    - name: Build kernel
      run: env GIT_FETCH=0 ARCH=${{ matrix.arch }} GIT_BRANCH=${{ matrix.branch }} PLATFORM=${{ matrix.platform }} BIS=${{ matrix.bis }} CROSS_COMPILE=yes ${GITHUB_WORKSPACE}/.github/bin/matrix-helper ${GITHUB_WORKSPACE}/rpi-kernel-build
    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: images-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}-${{ matrix.arch }}-${{ matrix.branch }}-${{ matrix.platform }}-bis${{ matrix.bis }}
        path: images/*.tar.xz
        if-no-files-found: ignore
