name: schedule
on:
  schedule:
  - cron: '34 5 * * 1'
  workflow_dispatch:
jobs:
  build:
    name: Build kernel (${{ matrix.arch }}, ${{ matrix.branch }}, ${{ matrix.platform }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - arm
        - arm64
        branch:
        - rpi-6.1.y
        - rpi-6.6.y
        platform:
        - bcm2709
        - bcm2711
        - bcmrpi
        - bcmrpi3
        exclude:
        - arch: arm
          platform: bcmrpi3
        - arch: arm64
          platform: bcm2709
        - arch: arm64
          platform: bcmrpi
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: raspberrypi/linux
        ref: ${{ matrix.branch }}
        path: linux
    - name: Dependency packages
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential flex bison libssl-dev perl rsync gcc-aarch64-linux-gnu libc6-dev-arm64-cross gcc-arm-linux-gnueabi libc6-dev-armel-cross
    - name: Build kernel
      run: env GIT_FETCH=0 ARCH=${{ matrix.arch }} GIT_BRANCH=${{ matrix.branch }} PLATFORM=${{ matrix.platform }} CROSS_COMPILE=yes ${GITHUB_WORKSPACE}/rpi-kernel-build
    - name: Upload images
      uses: actions/upload-artifact@v4
      with:
        name: images-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}-${{ matrix.arch }}-${{ matrix.branch }}-${{ matrix.platform }}
        path: images/*.tar.xz
        retention-days: 25
        include-hidden-files: true
